service: aws-speech-voxrec-function

frameworkVersion: ">=1.0.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: dev
  timeout: 10

custom:
  BUCKET: '****'
  HOOK_URL: '****'
  APP_KEY: '****'
  VOICEBASE_BEARER_TOKEN: '****'

functions:
  processFile:
      handler: handler.processFile
      environment:
        BUCKET: ${self:custom.BUCKET}
        HOOK_URL: ${self:custom.HOOK_URL}
        APP_KEY: ${self:custom.APP_KEY}
        VOICEBASE_BEARER_TOKEN: ${self:custom.VOICEBASE_BEARER_TOKEN}
      events:
        - s3: ${self:custom.BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .wav
